[pytest]
filterwarnings =
    ignore::DeprecationWarning:jupyter_client.connect
addopts = -vs
testpaths =
        test_case/test_contract_api
;        test_case/test_customer_api
;        test_case/test_login_api
;        test_case/test_user_business_api
;        test_case/test_auth.py
;        test_case/test_report.py
python_files = test*
python_classes = Test*
python_functions = test*
markers =
    smoke: 冒烟测试
    run: 执行顺序